#!/usr/bin/env python3
"""Generate AVR-friendly humid-air density correction lookup data.

Requires the host-only package pinned in requirements-tools.txt:
    python -m pip install -r requirements-tools.txt
    python tools/generate_air_density_table.py
"""
from pathlib import Path

import CoolProp
from CoolProp.HumidAirProp import HAPropsSI

MIN_C = -20
MAX_C = 80
STEP_C = 1
PRESSURE_PA = 101325.0
REFERENCE_C = 24.0
REFERENCE_RH = 0.5
OUTLET_RH = 1.0
OUTPUT = Path(__file__).resolve().parents[1] / "cat2" / "include" / "generated" / "air_density_table.h"


def density_kg_m3(temp_c: float, relative_humidity: float) -> float:
    return 1.0 / HAPropsSI("Vha", "T", 273.15 + temp_c, "P", PRESSURE_PA, "R", relative_humidity)


def main() -> None:
    rho24 = density_kg_m3(REFERENCE_C, REFERENCE_RH)
    corrections = [rho24 / density_kg_m3(temp_c, OUTLET_RH)
                   for temp_c in range(MIN_C, MAX_C + 1, STEP_C)]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by tools/generate_air_density_table.py; do not edit manually.",
        f"// CoolProp {CoolProp.__version__}; T={MIN_C}..{MAX_C} C, step={STEP_C} C.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <math.h>",
        "#if defined(__AVR__)",
        "#include <avr/pgmspace.h>",
        "#define CAT_AIR_DENSITY_PROGMEM PROGMEM",
        "#else",
        "#define CAT_AIR_DENSITY_PROGMEM",
        "#endif",
        "",
        f"static const int8_t AIR_DENSITY_TABLE_MIN_C = {MIN_C};",
        f"static const int8_t AIR_DENSITY_TABLE_MAX_C = {MAX_C};",
        f"static const uint8_t AIR_DENSITY_TABLE_STEP_C = {STEP_C};",
        f"static const uint8_t AIR_DENSITY_TABLE_COUNT = {len(corrections)};",
        f"static const float AIR_DENSITY_RHO24_KG_M3 = {rho24:.9g}f;",
        "static const float AIR_DENSITY_CORRECTION[AIR_DENSITY_TABLE_COUNT] CAT_AIR_DENSITY_PROGMEM = {",
    ]
    for offset in range(0, len(corrections), 6):
        lines.append("  " + ", ".join(f"{v:.9g}f" for v in corrections[offset:offset + 6]) + ",")
    lines.extend([
        "};",
        "",
        "inline float airDensityTableValue(uint8_t index) {",
        "#if defined(__AVR__)",
        "  return pgm_read_float_near(&AIR_DENSITY_CORRECTION[index]);",
        "#else",
        "  return AIR_DENSITY_CORRECTION[index];",
        "#endif",
        "}",
        "inline bool airDensityCorrectionAt(float temperatureC, float &correction) {",
        "  if (!(temperatureC >= AIR_DENSITY_TABLE_MIN_C && temperatureC <= AIR_DENSITY_TABLE_MAX_C)) { correction=NAN; return false; }",
        "  const float position=(temperatureC-AIR_DENSITY_TABLE_MIN_C)/AIR_DENSITY_TABLE_STEP_C;",
        "  uint8_t index=(uint8_t)position;",
        "  if (index >= AIR_DENSITY_TABLE_COUNT-1) { correction=airDensityTableValue(AIR_DENSITY_TABLE_COUNT-1); return true; }",
        "  const float fraction=position-index;",
        "  correction=airDensityTableValue(index)+(airDensityTableValue(index+1)-airDensityTableValue(index))*fraction;",
        "  return true;",
        "}",
        "inline bool airDensityRhoOutAt(float temperatureC, float &rhoOut) {",
        "  float correction; if (!airDensityCorrectionAt(temperatureC, correction) || correction <= 0.0f) { rhoOut=NAN; return false; }",
        "  rhoOut=AIR_DENSITY_RHO24_KG_M3/correction; return true;",
        "}",
        "#undef CAT_AIR_DENSITY_PROGMEM",
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT} with rho24={rho24:.9f} kg/m^3 ({len(corrections)} points)")


if __name__ == "__main__":
    main()
